---
- name: kernel update
  hosts: 10.0.2.15
  become: yes
  become_method: sudo
  tasks:
  - name: install repo
    ansible.builtin.yum:
      name: https://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
      state: present
  - name: update kernel
    ansible.builtin.yum:
      name: kernel-ml
      enablerepo: elrepo-kernel
  - name: post update
    ansible.builtin.reboot:
...
